config/routes.rb
HireCrm::Application.routes.draw do

  resources :records
  resources :search

  root :to => 'sessions#new'

  get 'login',     to: 'sessions#new',     as: 'login'
  post 'login',    to: 'sessions#login'
  get 'signup',    to: 'sessions#signup',  as: 'signup'
  post 'signup',   to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'dashboard', to: 'users#dashboard'

  post 'jobs/import_job' => 'jobs#import_job'
  get 'jobs/import_result' => 'jobs#import_result'

  get 'jobs/:id/state_action' => 'states#state_action', as: 'change_state'
  post 'jobs/:id/state_action' => 'states#state_action', as: 'change_state'

  get 'interviews/:interview_id/state_action' => 'states#state_action', as: 'change_state'
  post 'interviews/:interview_id/state_action' => 'states#state_action', as: 'change_state'

  post 'jobs/:id' => 'states#admin_like'

  resources :companies do 
    resources :jobs,
      :controller => 'companies/jobs',
      :only => [:new]
  end
  
  resources :jobs do 
    resources :interviews,
      :controller => 'jobs/interviews',
      :only => [:new]
  end

  resources :users do 
    resources :interviews,
      :controller => 'users/interviews',
      :only => [:new]
  end

  resources :interviews do
    resource :comment,
      :controller => 'interviews/comments',
      :only => [:new, :create]
  end

  
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id          :integer          not null, primary key
#  company_id  :integer
#  title       :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Job < ActiveRecord::Base
  attr_accessible :company_id, :description, :title

  belongs_to :company

  has_many :relationships
  has_many :interviews
  
  has_many :records, 		:through => :relationships
  has_many :users, 			:through => :relationships


  after_initialize :set_relationship_for_users

  #### uncomment to enable solar ####
  # searchable do
  #   text :title
  # end

  def relationship_for_user(user)
   @relationship_for_users[user.id] ||= if relationships.loaded?
     relationships.detect{|r| r.user_id == user.id}
   else
     relationships.where(:relationships => {:user_id => user.id}).first
    end
  end
  
  private
    def set_relationship_for_users
      @relationship_for_users ||= {}
    end

end

#<Job

app/controllers/companies/jobs_controller.rb
class Companies::JobsController < ApplicationController
	before_filter :logged_in?, :only => [:index, :show, :update, :new]
  
  # GET 	=> /companies/:company_id/jobs/new/
  def new
    @job     = Job.new
    @company = Company.find(params[:company_id])

    respond_to do |format|
      format.html
      format.json { render json: @interview }
    end
  end

end

app/controllers/jobs/interviews_controller.rb
class Jobs::InterviewsController < ApplicationController
  before_filter :logged_in_only?, :only => [:new, :create]

  # GET 	=> /jobs/:job_id/interviews/new/
  def new
    @interview = Interview.new
    @job 			 = Job.find(params[:job_id])
    @users 		 = User.all

    respond_to do |format|
      format.html
      format.json { render json: @interview }
    end
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :admin_only?, :only => [:destroy, :edit]
  before_filter :logged_in_only?, :only => [:create, :new, :show]
  skip_before_filter :verify_authenticity_token, :only => [:import_job]
  skip_before_filter :verify_logged_in, :only => [:import_job]

  ##################
  # Custom Actions #
  ##################

  def indeed_jobs
    @query = params[:query]
    @location = params[:location]

    if @query && @location
      @indeed_jobs = JobSearcher.indeed_search(@query, @location)
    end
  end

  ###################
  # RESTful Actions #
  ###################

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.includes(:relationships, :company).all
    # @company = Company.find(params[:company_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show

    @job        = Job.find(params[:id])
    @company    = @job.company
    @interview  = @job.relationships.where(:user_id => current_user.id).first
    @interviews = @job.interviews

    
    @relationship = @job.relationship_for_user(current_user)
    @state        = @relationship.aasm_state if @relationship

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new
    @companies = Company.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
    @company = Company.find(@job.company_id)
  end

  # POST  => /companies/:company_id/jobs/new/
  # POST  => /jobs/new/

  def create
    @job     = Job.new(params[:job])
    @company = Company.find(params[:job][:company_id])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def import_job
    @url = params[:url]
    @job = ChromeJobAdder.new(@url).create_job_from_link
    render :json => @job
  end

  def import_result
    
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Select A Company</label>
     <select name="job[company_id]">
       <% @companies.each do |c|%>
         <option value=<%= c.id %>><%= c.name %></option>
       <% end %>
     </select>
  </div>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/import_job.html.erb
test

app/views/jobs/import_result.html.erb
Hello World

app/views/jobs/indeed_jobs.html.erb
<br>

<%= form_tag("/jobs/indeed") do %>
	<%= label_tag(:query, "Search for:") %>
	<%= text_field_tag :query, @query, :placeholder => "Pick a keyword" %>

	<br>

	<%= label_tag(:location, "Location:") %>
	<%= text_field_tag :location, @location, :placeholder => "Pick a location"%>

	<br>
	
	<%= submit_tag "Find Jobs", :class => "btn btn-info" %>

<% end %>

<% if  @indeed_jobs %>

	<h3><%= "#{@query.capitalize} jobs in #{@location} from Indeed"%></h3>

	<table>
	  <tr>
	    <th>Job Title</th>
	    <th>Company</th>
	    <th>Snippet</th>
	    <th>URL</th>
	  </tr>

	<% @indeed_jobs.each do |job| %>
	  <tr>
	    <td><%= job["jobtitle"] %></td>
	    <td><%= job["company"] %></td>
	    <td><%= job["snippet"] %></td>
	    <td><%= link_to("link", job["url"])  %></td>
	  </tr>
	<% end %>
	</table>

<% end %>

app/views/jobs/index.html.erb
<h1>Available Jobs</h1>

<% if @jobs.empty? %>
  <p>There are no jobs in the system.</p>
<% else %>
  <%= render :partial => "shared/job_list", :locals => {:job_list => @jobs} %>
<% end %>

<%= link_to 'Add Job', new_job_path, :class => "btn btn-info" %>

app/views/jobs/new.html.erb
<h1>Create a New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<% if current_user.student? %>
  <%= render :partial => "shared/state_change_buttons",
  :locals => {:job => @job, :interview => @interview, :state => @state} %>
<% elsif current_user.admin? %>
  <%= render :partial => "shared/admin_like_button",
  :locals => {:job => @job, :state => @state} %>
<% end %>

<div class="row-fluid sortable">

  <div class="box span4">
    <div class="box-content pagination-centered company_logo_div">
      <%= image_tag @job.company.logo_url, :size => "200x200" %>
    </div>
  </div><!--/span-->
  <div class="box span8">
    <div class="box-content">
      <h1><%= @job.title %></h1>
      <p><%= @job.description %></p>               
     </div>
  </div><!--/span-->
</div><!--/row-->
<div class="row-fluid sortable">
  <div class="box span4">
    <div class="box-header">
      <h2><i class="icon-th"></i><span class="break"></span>Company Overview</h2>
    </div>
    <div class="box-content">
        <%= raw(@company.overview) %>             
    </div>
  </div><!--/span-->
  
      <div class="box span4">
        <div class="box-header">
          <h2><i class="fa-icon-rss green"></i><span class="break"></span>My Job History</h2>
        </div>
        <div class="box-content">
          <ul class="dashboard-list">
            <% @job.records.each do |record| %>
            <li>
              <!-- <i class="fa-icon-rss green">&nbsp;</i> -->
              <span class="dash_sidebar">
                  <%= record.event.description[0..-2] %> for <strong><%= record.job %></strong> at <span class="blue"><%= record.company %></span>.
              </span>

            </li>
            <% end %>
          </ul>
        </div>
      </div>
<!--/span-->
  
  <div class="box span4">
    <div class="box-header">
      <h2><i class="icon-th"></i><span class="break"></span>Other Jobs at <%= @job.company.name %></h2>
    </div>
    <div class="box-content">
    	<% other_jobs = @job.company.jobs - [@job] %>
      <% if !other_jobs.empty? %>
      <ul>
        <% other_jobs.each do |job| %>
          <li><%= link_to job.title, job_path(job) %></li>
        <% end %>
      </ul>  
      <% else %>   
        <p>There are currently no other job postings for this company.</p>
      <% end %>                
    </div>
  </div><!--/span-->
</div><!--/row-->
      
<hr>

<% if current_user.admin? %>
  <%= link_to 'Edit Job', edit_job_path(@job), :class => "btn btn-warning" %>
<% end %>