config/routes.rb
HireCrm::Application.routes.draw do

  resources :records
  resources :search

  root :to => 'sessions#new'

  get 'login',     to: 'sessions#new',     as: 'login'
  post 'login',    to: 'sessions#login'
  get 'signup',    to: 'sessions#signup',  as: 'signup'
  post 'signup',   to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'dashboard', to: 'users#dashboard'

  post 'jobs/import_job' => 'jobs#import_job'
  get 'jobs/import_result' => 'jobs#import_result'

  get 'jobs/:id/state_action' => 'states#state_action', as: 'change_state'
  post 'jobs/:id/state_action' => 'states#state_action', as: 'change_state'

  get 'interviews/:interview_id/state_action' => 'states#state_action', as: 'change_state'
  post 'interviews/:interview_id/state_action' => 'states#state_action', as: 'change_state'

  post 'jobs/:id' => 'states#admin_like'

  resources :companies do 
    resources :jobs,
      :controller => 'companies/jobs',
      :only => [:new]
  end
  
  resources :jobs do 
    resources :interviews,
      :controller => 'jobs/interviews',
      :only => [:new]
  end

  resources :users do 
    resources :interviews,
      :controller => 'users/interviews',
      :only => [:new]
  end

  resources :interviews do
    resource :comment,
      :controller => 'interviews/comments',
      :only => [:new, :create]
  end

  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  phone           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  role            :string(255)
#  hireable        :boolean
#

class User < ActiveRecord::Base

  attr_accessible :email, :name, :phone, :password, :password_confirmation, :role, :hireable

  has_many :relationships
  has_many :interviews
  
  has_many :companies, 	:through => :relationships
  has_many :jobs, 		 	:through => :relationships
  has_many :records, 		:through => :relationships
  has_many :comments

  # Validation of attributes #

  validates_presence_of   :name
  validates_presence_of   :email

  validates_uniqueness_of :email

  has_secure_password
  validates :password,
    :presence => true,
    :confirmation => true

  after_initialize :set_relationship_for_jobs

  ##########################
  # Authentication Methods #
  ##########################

  def admin?
    self.role == "admin"
  end

  def student?
    self.role == "student"
  end

  def guest?
    self.role == "guest"
  end

  #### uncomment to enable solar ####
  # searchable do
  #   text :name
  # end
  
  def relationship_for_job(job)
    @relationship_for_jobs[job.id] ||= if relationships.loaded?
      relationships.detect{|r| r.job_id == job.id }
    else
      relationships.where(:relationships => {:job_id => job.id}).first
    end
  end
  
  private
    def set_relationship_for_jobs
      @relationship_for_jobs ||= {}
    end
end

app/controllers/users/interviews_controller.rb
class Users::InterviewsController < ApplicationController
  before_filter :logged_in_only?, :only => [:new, :create, :update, :show]

  # GET 	=> /users/:user_id/interviews/new/
  def new
    @interview = Interview.new
    @jobs 		 = Job.all
    @user 		 = User.find(params[:user_id])

    respond_to do |format|
      format.html
      format.json { render json: @interview }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :admin_only?, :only => [:index, :dashboard, :new, :create, :destroy]
  before_filter :current_user_only?, :only => [:edit, :show]
  
  helper_method :get_calendar_data
  helper_method :interviews_past
  helper_method :interviews_future
  helper_method :interviews_chart
  helper_method :interviews_chart_dates

  def dashboard
    @interviews = Interview.all
    @users = User.all

    # Calendar view data

    gon.interview  = get_calendar_data(@users)
    gon.chart_data, gon.axis_data = interviews_chart

    # boilerplate rails code
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    # authorize! if can? :manage, @user

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    gon.interview  = collect_calendar_data(@user.interviews)
    @relationships = @user.relationships

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
      format.js { render @user}
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        UserMailer.signup_confirmation(@user).deliver
        format.html { redirect_to @user, notice: "#{@user.name} was successfully created." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  ##################
  # HELPER METHODS #
  ##################

  def interviews_past
    DateTime.now - 6
  end

  def interviews_future
    DateTime.now + 12
  end

  def interviews_chart
    interview_array = []
    axis_array      = []

    (interviews_past..interviews_future).step(1).each_with_index do |date, index| 
      interview_count = Interview.where(:date => date.strftime("%Y-%m-%d")).count 
      interview_array << [index, interview_count]
      axis_array << [index, date.strftime("%b-%d")]
    end
    
    return interview_array, axis_array
  end

  def get_calendar_data(users)
    json_interviews = []

    users.each do |user|
      json_interviews << collect_calendar_data(user.interviews) 
    end

    json_interviews.flatten
  end

  def collect_calendar_data(interviews)
    interviews.collect do |interview|
      {
        :title => "#{interview.company.name} interview  (#{interview.user.name})",
        :start => interview.merge_datetime,
        :url => interview_path(interview),
        :allDay => false
      }
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper


  def random_avatar
    octocats = ["http://octodex.github.com/images/daftpunktocat-thomas.gif",
                "http://octodex.github.com/images/daftpunktocat-thomas.gif",
                "http://octodex.github.com/images/daftpunktocat-thomas.gif",
                "http://octodex.github.com/images/daftpunktocat-thomas.gif",
                "http://octodex.github.com/images/daftpunktocat-thomas.gif",
                "http://octodex.github.com/images/daftpunktocat-thomas.gif",
                "http://octodex.github.com/images/daftpunktocat-thomas.gif",
                "http://octodex.github.com/images/daftpunktocat-thomas.gif",
                "http://octodex.github.com/images/daftpunktocat-thomas.gif",
                "http://octodex.github.com/images/daftpunktocat-thomas.gif",
                "http://octodex.github.com/images/nyantocat.gif"
              ]
    num = octocats.length
    octocats[rand(num)]
  end

  # Employment Statistics

  def students_hireable
    User.where(:role => "student", :hireable => true)
  end

  def number_students_hireable
    students_hireable.count
  end

  def students_employed
    students_hireable.select{|u| u.relationships.where(:aasm_state => "offer_accepted").any? }.count
  end

  def display_employed_students
    (students_employed / number_students_hireable.to_f) * 100
  end

  def students_receiving_offers
    students_hireable.select{|u| u.relationships.where('aasm_state = "offer_received" or aasm_state = "offer_accepted" or aasm_state = "offer_declined"').any? }.count
  end

  def display_students_receiving_offers
    (students_receiving_offers / number_students_hireable.to_f) * 100
  end

  # Interviewing Statistics

  def total_students
    User.where(:role => 'student').count
  end

  def total_students_interviewing
    students_hireable.select{|u| u.student? && u.interviews.any? }.count
  end

  def percentage_not_interviewing
    ((total_students - total_students_interviewing) / total_students.to_f * 100)
  end

  def percentage_interviewing
    100 - percentage_not_interviewing
  end

  def interviews_completed
    Interview.where("date < ?", Date.current).count
  end

 def total_likes
    records = Record.all
    records.select {|record| record.event_id == 1}.count
  end

  def offers_made
    records = Record.all
    records.select {|record| record.event_id == 5}.count
  end

  def offers_accepted
    records = Record.all
    records.select {|record| record.event_id == 8}.count
  end

  def offers_rejected
    records = Record.all
    records.select {|record| record.event_id == 9}.count
  end

  # Company Methods

  def hotlist_jobs(user)
    decline_states = ["start", "user_decline", "company_decline", "offer_declined"]
    user.relationships.reject {|rel| decline_states.include?(rel.aasm_state)}    
  end

  def active_jobs(user)
    accept_states = ["interviewing", "pending", "offer_received"]
    user.relationships.select {|rel| accept_states.include?(rel.aasm_state)}    
  end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <% if current_user.admin? %>
    <div class="field">
      <%= f.label :role %>
      <%= f.text_field :role %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :hireable %>
    <%= f.check_box :hireable %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="input-prepend" title="Password">
    <span class="add-on"><i class="icon-lock"></i></span>
    <input class="input-large span10" id="password" name="user[password]" type="password" placeholder="Password"/>
  </div>

  <div class="clearfix"></div>

  <div class="input-prepend" title="Password_Confirmation">
    <span class="add-on"><i class="icon-lock"></i></span>
    <input class="input-large span10" id="password_confirmation" name="user[password_confirmation]" type="password" placeholder="Confirm Password"/>
  </div>
  
  <div class="actions">
    <%= f.submit 'Submit', :class => "btn btn-success" %>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<div class="row-fluid">
  <div class="circleStats">

    <div class="span3" onTablet="span3" onDesktop="span3">
      <div class="circleStatsItem green">
        <i class="fa-icon-thumbs-up"></i>
        <span class="percent">%</span>
        <input type="text" value="<%= display_employed_students %>" class="greenCircle" />
      </div>
      <div class="box-small-title">Employed Students</div>
    </div>

    <div class="span3" onTablet="span3" onDesktop="span3">
      <div class="circleStatsItem yellow">
        <i class=" fa-icon-star"></i>
        <span class="percent">%</span>
        <input type="text" value="<%= display_students_receiving_offers %>" class="yellowCircle" />
      </div>
      <div class="box-small-title">Students Receiving Offers</div>
    </div>

    <div class="span3" onTablet="span3" onDesktop="span3">
      <div class="circleStatsItem blue">
        <i class="fa-icon-user"></i>
        <span class="percent">%</span>
        <input type="text" value="<%= percentage_interviewing %>" class="blueCircle" />
      </div>
      <div class="box-small-title">Students Interviewing</div>
    </div>

    <div class="span3" onTablet="span3" onDesktop="span3">
      <div class="circleStatsItem orange">
        <i class="fa-icon-warning-sign"></i>
        <span class="percent">%</span>
        <input type="text" value="<%= percentage_not_interviewing %>" class="orangeCircle" />
      </div>
      <div class="box-small-title">Students Without Interviews</div>
    </div>

  </div>
</div>
      
<div class="row-fluid sortable">
  <div class="box span8">
    <div class="box-header">
      <h2><i class="icon-list-alt"></i><span class="break"></span>Interviews Activity</h2>
      <div class="box-icon">
        <a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
        <a href="#" class="btn-close"><i class="icon-remove"></i></a>
      </div>
    </div>
    <div class="box-content">
      <div id="stats-chart"  class="center" style="height:300px;" ></div>
    </div>
  </div>

  <div class="box span4">
    <div class="box-header">
      <h2><i class="icon-list"></i><span class="break"></span>Total Stats</h2>
      <div class="box-icon">
        <a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
        <a href="#" class="btn-close"><i class="icon-remove"></i></a>
      </div>
    </div>
    <div class="box-content">
      <ul class="dashboard-list">
        <li>
          <a><i class="fa-icon-comment green"></i>
            <span class="green"><%= Interview.count %></span>
            Interviews Added
          </a>
        </li>
        <li>
          <a><i class="fa-icon-ok yellow"></i>
          <span class="yellow"><%= interviews_completed %></span>
          Interviews Completed
        </a>
        </li>
        <li>
          <a><i class="fa-icon-th blue"></i>
          <span class="blue"><%= Job.count %></span>
          Jobs Added
        </a>
        </li>
        <li>
          <a><i class="fa-icon-heart red"></i>                     
          <span class="red"><%= total_likes %></span>
          Jobs Liked
        </a>
        </li>
        <li>
          <a><i class="fa-icon-th-large yellow"></i>
          <span class="yellow"><%= Company.count %></span>
          Companies Added
        </a>
        </li>
        <li>
          <a><i class="fa-icon-star blue"></i>
          <span class="blue"><%= offers_made %></span>
          Offers Made
        </a>
        </li>
        <li>
          <a>
          <i class="fa-icon-glass green"></i>
          <span class="green"><%= offers_accepted %></span>
          Offers Accepted</a>
        </li>
        <li>
          <a>
          <i class="fa-icon-remove red"></i>
          <span class="red"><%= offers_rejected %></span>
          Offers Rejected</a>
        </li>        
      </ul>
  </div>
</div>

<div class="row-fluid sortable">
  <div class="box span12">
      <div id="myTabContent" class="tab-content">
        <div class="tab-pane active" id="calendar_tab">
          <div class="row-fluid">
            <%= render 'shared/calendar12' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit <%= @user.name %></h1>

<%= render 'form' %>

<% if current_user.student? %>
	<%= link_to 'Cancel', user_path(current_user) %>
<% else %>
	<%= link_to 'Cancel', users_path %>
<% end %>

app/views/users/index.html.erb
<h1>Flatiron Students</h1>
<div class="row-fluid sortable">    
  <div class="box span12">
    <div class="box-header" data-original-title>
      <h2><i class="icon-user"></i><span class="break"></span>Student List</h2>
      <div class="box-icon">
        <a href="#" class="btn-setting"><i class="icon-wrench"></i></a>
        <a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
        <a href="#" class="btn-close"><i class="icon-remove"></i></a>
      </div>
    </div>
    <div class="box-content">
      <table class="table table-striped table-bordered bootstrap-datatable datatable">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Actions</th>
          </tr>
        </thead>   
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.name, user %></td>
              <td><%= user.email %></td>
              <td><%= user.phone %></td>
               <td class="center">
              <a class="btn btn-success" href="<%= user_path(user) %>">
                <i class="icon-zoom-in icon-white"></i>  
              </a>
              <a class="btn btn-info" href="<%= edit_user_path(user) %>">
                <i class="icon-edit icon-white"></i>  
              </a>
                <%= link_to raw('<i class="icon-trash icon-white"></i>'), user, :class => 'btn btn-danger', :confirm => "Are you sure you want to delete this?", :method => :delete %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>   
      <% if current_user.admin? %>
        <%= link_to 'Add Student', new_user_path, :class => "btn btn-warning" %>
      <% end %>         
  </div>
</div>
</div>
<hr>

app/views/users/new.html.erb
<h1>Registration</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row-fluid">
  <div class="pull-left">
    <span class = "gravatar-show-page"><%= gravatar_image_tag(@user.email, :alt => @user.name, :class => "gravatar-image", :gravatar => { :default => random_avatar }) %></span>
  </div>
  <div class="pull-left">
    <span>
      <span class="user-contact-name">
        <%= @user.name %><br>
      </span>
      <i class="fa-icon-envelope-alt user-contact-icon"></i><span class="user-contact-text"> <%= @user.email %></span></span> &nbsp&nbsp <span><i class="fa-icon-phone user-contact-icon"></i><span class="user-contact-text"> <%= @user.phone %></span><br>
      <%= link_to 'Add Interview', new_user_interview_path(@user), :class => "btn btn-info user-contact-button" %>
    </span>
  </div>
</div>


<div class="row-fluid">
        
  <div class="box span8">
    <div class="box-header">
      <h2><i class="icon-th"></i> Upcoming Interviews</h2>
    </div>
    <div class="box-content">
      <ul class="nav tab-menu nav-tabs" id="myTab">
        <li class="active"><a href="#calendar_tab">Calendar View</a></li>
        <li><a href="#list">List View</a></li>
      </ul>
       
      <div id="myTabContent" class="tab-content">
        <div class="tab-pane active" id="calendar_tab">
          <div class="row-fluid">

            <%= render 'shared/calendar_embed' %>

          </div>
        </div>
        <div class="tab-pane" id="list">
          <div class="row-fluid">    
            <div class="box span12">
              <div class="box-content">
                <table class="table table-striped table-bordered bootstrap-datatable datatable">
                  <thead>
                    <tr>
                      <th>Company Name</th>
                      <th>Job Title</th>
                      <th>Date</th>
                      <th>Time</th>
                      <th>Status</th>
                      <th>Actions</th>
                    </tr>
                  </thead>   
                  <tbody>

                  <% if @user.interviews.empty? == true %>
                    <p><%= @user.name %> has no upcoming interviews.</p>
                  <% else %>

                    <% @user.interviews.each do |interview| %>

                      <tr>
                        <td><%= interview.company.name %></td>
                        <td><%= interview.job.title %></td>
                        <td><%= interview.date.strftime('%-m/%-d/%Y') %></td>
                        <td><%= interview.start_time.strftime('%-l:%M %P') %></td>
                        

                        <td class="center">
                          <%= span_for_job_relationship_status(interview.job, current_user) %>
                        </td>

                        <td class="center">

                          <a class="btn btn-success" href="<%= interview_path(interview) %>">
                            <i class="icon-zoom-in icon-white"></i>  
                          </a>

                          <a class="btn btn-info" href="<%= edit_interview_path(interview) %>">
                            <i class="icon-edit icon-white"></i>  
                          </a>

                          <%= link_to raw('<i class="icon-trash icon-white"></i>'), interview, :class => 'btn btn-danger', :confirm => "Are you sure you want to delete this?", :method => :delete %>
                        </td>
                      </tr>
                    <% end %>
                  <% end %>
                  </tbody>
                </table>            
              </div>
            </div><!--/span-->
          </div><!--/row-->
        </div>
      </div>
    </div>
  </div><!--/span-->

  <div class="box span4">
    <div>
      <div class="box-header">
      </div>
      <%= render "shared/hotlist", :user => @user %>
    <hr><!-- end Liked Companies // begin News Feed-->
    <div>
      <div class="box-header">
        <h2><i class="fa-icon-rss green"></i><span class="break"></span>News Feed</h2>
      </div>
      <div class="box-content">
        <ul class="dashboard-list">
          <% @user.records.each do |record| %>
          <li>
            <!-- <i class="fa-icon-rss green">&nbsp;</i> -->
            <span class="dash_sidebar">
                <%= record.event.description[0..-2] %> for <strong><%= record.job %></strong> at <span class="blue"><%= record.company %></span>.
            </span>

          </li>
          <% end %>
        </ul>
      </div>
    </div>
  
  </div>
  </div>
</div>