config/routes.rb
HireCrm::Application.routes.draw do

  resources :records
  resources :search

  root :to => 'sessions#new'

  get 'login',     to: 'sessions#new',     as: 'login'
  post 'login',    to: 'sessions#login'
  get 'signup',    to: 'sessions#signup',  as: 'signup'
  post 'signup',   to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'dashboard', to: 'users#dashboard'

  post 'jobs/import_job' => 'jobs#import_job'
  get 'jobs/import_result' => 'jobs#import_result'

  get 'jobs/:id/state_action' => 'states#state_action', as: 'change_state'
  post 'jobs/:id/state_action' => 'states#state_action', as: 'change_state'

  get 'interviews/:interview_id/state_action' => 'states#state_action', as: 'change_state'
  post 'interviews/:interview_id/state_action' => 'states#state_action', as: 'change_state'

  post 'jobs/:id' => 'states#admin_like'

  resources :companies do 
    resources :jobs,
      :controller => 'companies/jobs',
      :only => [:new]
  end
  
  resources :jobs do 
    resources :interviews,
      :controller => 'jobs/interviews',
      :only => [:new]
  end

  resources :users do 
    resources :interviews,
      :controller => 'users/interviews',
      :only => [:new]
  end

  resources :interviews do
    resource :comment,
      :controller => 'interviews/comments',
      :only => [:new, :create]
  end

  
end

app/views/shared/_calendar.html.erb
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-header" data-original-title>
      <h2><i class="icon-calendar"></i><span class="break"></span>Calendar</h2>
    </div>
    <div class="box-content">
    <div id="external-events" class="span3 hidden-phone hidden-tablet">
      <h4>Draggable Events</h4>
      <div class="external-event badge">Default</div>
      <div class="external-event badge badge-success">Completed</div>
      <div class="external-event badge badge-warning">Warning</div>
      <div class="external-event badge badge-important">Important</div>
      <div class="external-event badge badge-info">Info</div>
      <div class="external-event badge badge-inverse">Other</div>
      <p>
      <label for="drop-remove"><input type="checkbox" id="drop-remove" /> remove after drop</label>
      </p>
      </div>

      <div id="calendar" class="span9"></div>

      <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/shared/_calendar12.html.erb
<div class="box span12" onTablet="span12" onDesktop="span12">
  <div class="box-header">
    <h2><i class="icon-calendar"></i><span class="break"></span>Calendar</h2>
  </div>
  <div class="box-content">
    <div id="calendar" class="hidden-phone"></div>
    <div id="calendar" class="hidden-desktop hidden-tablet"></div>
    <div class="clearfix"></div>
  </div>  
</div><!--/span-->

app/views/shared/_calendar8.html.erb
<div class="box span8" onTablet="span12" onDesktop="span8">
  <div class="box-header">
    <h2><i class="icon-calendar"></i><span class="break"></span>Calendar</h2>
  </div>
  <div class="box-content">
    <div id="calendar" class="hidden-phone"></div>
    <div id="calendar" class="hidden-desktop hidden-tablet"></div>
    <div class="clearfix"></div>
  </div>  
</div><!--/span-->


      

app/views/shared/_calendar_embed.html.erb
<div class="box-tab span12" onTablet="span12" onDesktop="span12">
  <div class="box-tab-header">
  </div>
  <div class="box-content">
    <div id="calendar" class="hidden-phone"></div>
    <div id="calendar" class="hidden-desktop hidden-tablet"></div>
    <div class="clearfix"></div>
  </div>  
</div><!--/span-->

app/views/shared/_datetime_picker.html.erb
<label>Date:</label>
<input id="datepicker" type="text" value="<%= @interview.date.strftime('%m/%d/%Y') if !@interview.date.nil? %>">

<div class="field">
  <%= f.hidden_field :date, :id => "alt-datepicker"%>
</div>

<div class="input-append bootstrap-timepicker">
    <% if !@interview.start_time.nil? %>
    <%= f.text_field :start_time, { :class => "input-small", :id => "interview_start_time", :value => @interview.start_time.strftime('%I:%M %p') } %>
  <% else %>
    <%= f.text_field :start_time, { :class => "input-small", :id => "interview_start_time" } %>
  <% end %>
  <span class="add-on"><i class="icon-time"></i></span>
</div>

<div class="input-append bootstrap-timepicker">
  <% if !@interview.end_time.nil? %>
    <%= f.text_field :end_time, { :class => "input-small", :id => "interview_end_time", :value => @interview.end_time.strftime('%I:%M %p') } %>
  <% else %>
    <%= f.text_field :end_time, { :class => "input-small", :id => "interview_end_time"} %>
  <% end %>
  <span class="add-on"><i class="icon-time"></i></span>
</div>

<script type="text/javascript">
	$(function() {
	  $('#datepicker').datepicker({ 
	  		dateFormat: 'mm/dd/yy',
	  		altFormat: 'yy-mm-dd',
        numberOfMonths: 2,
	  		altField  : '#alt-datepicker'
	  	});
	});
  $('#interview_start_time').timepicker({
      defaultTime: '08:00 AM'
  });
  $('#interview_end_time').timepicker({
    defaultTime: '12:00 PM'
  });
</script>

app/views/shared/_event_history.html.erb
<h4>Event History</h4>

<% if current_user.admin? %>

		<% if @company.records.empty? == true %>
			<p><%= @company.name %> has no event history.</p>

		<% else %>
		<ul>
			<% @company.records.each do |record| %>
			<li> 
				<%= record.event %>
			</li>
			<% end %>
		</ul>
		<% end %>

<% elsif current_user? %>
		<% if @company.records.where("user_id=#{current_user.id}").empty? == true %>
			<p>You have no current event history at <%= @company.name %>.</p>

		<% else %>
		<ul>
			<% @company.records.where("user_id=#{current_user.id}").each do |record| %>
			<li> 
				<%= record.event %>
			</li>
			<% end %>
		</ul>
		<% end %>

<% else %>
	You have no current event history at <%= @company.name %>

<% end %>

app/views/shared/_header.html.erb
<div id="wrapper">

	<body>
<!-- 		<div id="overlay">
		<ul>
		  <li class="li1"></li>
		  <li class="li2"></li>
		  <li class="li3"></li>
		  <li class="li4"></li>
		  <li class="li5"></li>
		  <li class="li6"></li>
		</ul>
	</div>	 -->

	<!-- START: Header -->

	<div class="navbar">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<a class="brand" href="#"> <span class="hidden-phone">Hire Me</span></a>
								
				<!-- START: Header Menu -->

				<div class="nav-no-collapse header-nav">
					<ul class="nav pull-right">
						
						<!-- START: User Dropdown -->

						<% if current_user %>
             <span class = "pull-right">

               <span class="dropdown">

								<a class="btn dropdown-toggle" data-toggle="dropdown">
									<i class="icon-user icon-white"></i>
									<span class="caret"></span>
								</a>

								<ul class="dropdown-menu">
									<li><a href="<%= edit_user_path(current_user) %>"><i class="icon-user"></i> Edit Profile</a></li>
									<li><%= link_to raw('<i class="icon-off"></i> Logout'), logout_path, method: "delete"%></li>
								</ul>

								<a href="<%= user_path(current_user) %>" class = "remove-hyperlink">Hello, <%= current_user.name.split.first %>!</a>

							</span>

             </span>
           <% else %>
             <span class = "pull-right">
             <%= link_to "Sign up", signup_path, :class => "btn btn-success" %>  <%= link_to "Log in", login_path, :class => "btn btn-primary" %>
             </span>
           <% end %>

						<!-- END: User Dropdown -->

					</ul>
				</div>

				<!-- END: Header Menu -->
				
			</div>
		</div>
	</div>

	<!-- END: Header -->
	
	<div class="container-fluid">
		<div class="row-fluid">
				
			<!-- start: Main Menu -->

			<div class="span2 main-menu-span">
				<div class="nav-collapse sidebar-nav">
					<ul class="nav nav-tabs nav-stacked main-menu">

						<% if current_user.student? %>
							<%= nav_link raw('<i class="icon-home icon-white"></i><span class="hidden-tablet"> Home</span>'), user_path(current_user), {:class => 'link'}, {:wrapper => 'li', :wrapper_class => 'test-wrapper', :selected_class => 'active'} %>
						<% end %>

						<% if current_user.admin? %>
							<%= nav_link raw('<i class="icon-home icon-white"></i><span class="hidden-tablet"> Dashboard</span>'), dashboard_path, {:class => 'link'}, {:wrapper => 'li', :wrapper_class => 'test-wrapper', :selected_class => 'active'} %>
						<% end %>

						<% if current_user.admin? %>
							<%= nav_link raw('<i class="icon-user icon-white"></i><span class="hidden-tablet"> Students</span>'), users_path, {:class => 'link'}, {:wrapper => 'li', :wrapper_class => 'test-wrapper', :selected_class => 'active'} %>
						<% end %>

						<%= nav_link raw('<i class="icon-briefcase icon-white"></i><span class="hidden-tablet"> Companies</span>'), companies_path, {:class => 'link'}, {:wrapper => 'li', :wrapper_class => 'test-wrapper', :selected_class => 'active'} %>

						<%= nav_link raw('<i class="fa-icon-laptop icon-white"></i><span class="hidden-tablet"> Jobs</span>'), jobs_path, {:class => 'link'}, {:wrapper => 'li', :wrapper_class => 'test-wrapper', :selected_class => 'active'} %>

						

							<%= nav_link raw('<i class="icon-calendar icon-white"></i> <span class="hidden-tablet"> Interviews</span>'), interviews_path, {:class => 'link'}, {:wrapper => 'li', :wrapper_class => 'test-wrapper', :selected_class => 'active'} %>

							<% if current_user.admin? %>

							<%= nav_link raw('<i class="fa-icon-list-ol icon-white"></i> <span class="hidden-tablet"> Records</span>'), records_path, {:class => 'link'}, {:wrapper => 'li', :wrapper_class => 'test-wrapper', :selected_class => 'active'} %>
						<% end %>
						
					</ul>
				</div><!--/.well -->
			</div><!--/span-->
			<!-- end: Main Menu -->
			
			<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">Warning!</h4>
					<p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
				</div>
			</noscript>
			
			<div id="content" class="span10">
			<!-- start: Content -->
			
			<hr>

			<div>
				
				<div class="row-fluid">
					<div class="span12">

					<!-- header breadcrumb -->
					<div class="pull-left">
						<ul class="breadcrumb">
							<li>
								<a href="<%= current_user.role == "admin" ? dashboard_path : user_path(current_user) %>">Home</a> <span class="divider">/</span>
							</li>
							<li>
								<a href="#"><%= controller_name.capitalize %></a>
							</li>
						</ul>
					</div>

					<!-- search box -->

					<!-- </div> -->

					</div>
				</div>
			</div>
		<hr>

app/views/shared/_hotlist.html.erb
      <div class="box-content">
      <ul class="nav tab-menu nav-tabs dash" id="myTab">
        <li class="active"><a href="#liked_tab"><i class="fa-icon-heart red"></i><span class="hidden-tablet hidden-phone hidden-activity-buttons"> Liked Jobs</span></a></li>
        <li><a href="#interview_tab"><i class="fa-icon-laptop green"></i><span class="hidden-tablet hidden-phone hidden-activity-buttons"> Active Jobs</span></a></li>
      </ul>
      <div id="myTabContent" class="tab-content">
        <div class="tab-pane active" id="liked_tab">
          <div class="row-fluid">  
            <ul class = "dashboard-list">
              <% hotlist_jobs(@user).each do |rel| %>
                <li>
                  <span class="dash_sidebar">
                      <%= link_to rel.company.name, company_path(rel.company)%>
                    - <strong><%= link_to rel.job.title, job_path(rel.job), :class => "blue"%></strong>
                    <br>

                    <td class="center">
                      <%= span_for_job_relationship_status(rel.job, current_user) %>
                    </td>

                  </span>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="tab-pane" id="interview_tab">
          <div class="row-fluid">  
            <ul class = "dashboard-list">
              <% active_jobs(@user).each do |rel| %>
                <li>
                  <span class="dash_sidebar">
                      <%= link_to rel.company.name, company_path(rel.company)%>
                    - <strong><%= link_to rel.job.title, job_path(rel.job), :class => "blue"%></strong>
                    <br>
                    <td class="center">
                      <%= span_for_job_relationship_status(rel.job, current_user) %>
                    </td>
                  </span>
                </li>
              <% end %>
            </ul>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_interview_list.html.erb
<div class="row-fluid sortable">		
	<div class="box span12">
		<div class="box-header" data-original-title>
			<h2><i class="icon-user"></i><span class="break"></span>Interviews</h2>
			<div class="box-icon">
				<a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
				<a href="#" class="btn-close"><i class="icon-remove"></i></a>
			</div>
		</div>
		<div class="box-content">
			<table class="table table-striped table-bordered bootstrap-datatable datatable">
			  <thead>
				  <tr>
					  <th>Name</th>
					  <th>Company</th>
					  <th>Job Title</th>
					  <th>Date</th>
					  <th>Time</th>
					  <th>Status</th>
					  <th>Actions</th>
				  </tr>
			  </thead>   
			  <tbody>

			  <% interview_list.each do |interview| %>
			  	
			  	<tr>
						<td><%= interview.user.name %></td>
						<td><%= interview.company.name %></td>
						<td><%= interview.job.title %></td>
						<td><%= interview.date.strftime('%-m/%-d/%Y') %></td>
						<td><%= interview.start_time.strftime('%-l:%M %P') %></td>
						<td><%= span_for_job_relationship_status(interview.job, interview.user) %></td>

						
						<td class="center">
							<a class="btn btn-success" href="<%= interview_path(interview) %>">
								<i class="icon-zoom-in icon-white"></i>  
							</a>
							<a class="btn btn-info" href="<%= edit_interview_path(interview) %>">
								<i class="icon-edit icon-white"></i>  
							</a>
							<%= link_to raw('<i class="icon-trash icon-white"></i>'), interview, :class => 'btn btn-danger', :confirm => "Are you sure you want to delete this?", :method => :delete %>
							</td>
						</tr>
				<% end %>
			  </tbody>
		  </table>            
		</div>
	</div>
</div>

app/views/shared/_interviews.html.erb
<ul>
		<% interview_list.interviews.each do |interview| %>
			<li>
				<%= interview.company.name %>, <%= interview.job.title %>, <%= interview.date.strftime("%m/%d/%Y") %> at <%= interview.start_time.strftime("%I:%M%p") %> (<%= distance_of_time_in_words_to_now("#{interview.date} + #{interview.start_time}") %> from now)
			</li>
		<% end %>
</ul>

app/views/shared/_job_button_logic.html.erb
<% if @state.nil? || @state == "start" %>
  <%= link_to 'Like This Job', {:controller => :states, :action => :like_company}, :class => "btn btn-success status_btn" %>
<% else %> 
  <%= link_to 'Unlike Job', {:controller => :states, :action => :unlike_company}, :class => "btn status_btn" %>
  <%= link_to 'Add Interview', new_job_interview_path(@job), :class => "btn btn-info" %>
<% end %>

<span class="pull-right">
  <p style="font-style: italic">
    <% unless @relationship.nil? %>
      <% case @relationship.aasm_state %>
      <% when "like" %>
        You like this job!
      <% when "start" %>
        You have no relationship with this job.
      <% else %>  
        <% unless @relationship.interview.nil? %>  
          <% case @relationship.aasm_state %>
            <% when "interviewing" %>
                You have an interview scheduled with <%= @job.company.name %>! <%= link_to '(Update)', interview_path(@relationship.interview) %>
            <% when "pending" %>
              You interviewed with <%= @job.company.name %>! <%= link_to '(Update)', interview_path(@relationship.interview) %>
            <% when "company_decline" %>
              Talks with <%= @job.company.name %> didn't bear fruit. <%= link_to '(Update)', interview_path(@relationship.interview) %>
            <% when "offer_received" %>
              You received an offer from <%= @job.company.name %>! <%= link_to '(Update)', interview_path(@relationship.interview) %>
            <% when "offer_accepted" %>
              You accepted an offer from <%= @job.company.name %>! <%= link_to '(Update)', interview_path(@relationship.interview) %>
            <% else "offer_declined" %>
              You declined an offer from <%= @job.company.name %>. <%= link_to '(Update)', interview_path(@relationship.interview) %>
          <% end %>
        <% end%>
      <% end %>
    <% end %>
  </p>
</span>

app/views/shared/_records.html.erb
<div class="box span4 noMargin" onTablet="span12" onDesktop="span4">
  <div class="box-header">
    <h2><i class="fa-icon-list-ol"></i><span class="break"></span><%= @user.name.split.first %>'s Records</h2>
    <div class="box-icon">
      <a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
      <a href="#" class="btn-close"><i class="icon-remove"></i></a>
    </div>
  </div>
  <% r = @user.records.first %>
  <div class="box-content">
    <ul class="tickets">
      <li class="ticket">
        <a href="#">
          <span class="header">
            <span class="title">Status: <%= r.relationship.aasm_state %></span>
            <span class="title"><%= r.job %></span>
          </span> 
          <span class="content">
            <span class="avatar"><img src="img/avatar6.jpg" alt="Avatar"></span>
            <span class="name">Ashley Tan</span>
            <span class="priority blue">[ Low priority ]</span>
            <span class="status">Status: <span class="green">[ Complete ]</span></span>
            <span class="date">Jul 25, 2012 11:09</span>
          </span>                                                         
        </a>
      </li>
    </ul>
  </div>
</div><!--/span-->

app/views/shared/_relationship_state.html.erb
<% case @state %>
<% when "start" %>
  <%= link_to 'Like This Job', {:controller => :states, :action => :rel_like_company}, :class => "btn btn-success status_btn" %>
  <%= link_to 'Add Interview', new_job_interview_path(@relationship.job), :class => "btn btn-info" %>
<% when "like" %>
  <%= link_to 'Unlike Job', {:controller => :states, :action => :rel_unlike_company}, :class => "btn status_btn" %>
  <%= link_to 'Add Interview', new_job_interview_path(@relationship.job), :class => "btn btn-info" %>
<% when "interviewing" %>
  <%= link_to 'Edit Interview', edit_interview_path(@relationship.interview_id), :class => "btn btn-warning" %>
<% when "pending" %>
  <!-- Add Additional Interview -->
  <%= link_to 'Add Another Interview', new_job_interview_path(@relationship.job), :class => "btn btn-info status_btn" %>
  
  <!-- Offer Received -->
  <%= link_to 'Offer Received!', {:controller => :states, :action => :rel_offer_received}, :class => "btn btn-success status_btn" %>

  <!-- User Declines  -->
  <%= link_to 'You Declined', {:controller => :states, :action => :rel_user_declined}, :class => "btn btn-warning status_btn" %>

  <!-- Company Declines -->
  <%= link_to 'Rejected', {:controller => :states, :action => :rel_company_declined}, :class => "btn btn-danger status_btn" %>

<% when "user_decline" %>
  <span class="pull-right">
    <p style="font-style: italic">
      You declined to continue discussing the <%= @relationship.job.title %> position at <%= @relationship.company.name %>.
    </p>
  </span>

<% when "company_decline" %>
  <span class="pull-right">
    <p style="font-style: italic">
      <%= @relationship.company.name %> has passed (for now).
    </p>
  </span>

<% when "offer_received" %>
  <%= link_to 'Accept Offer', {:controller => :states, :action => :accept_offer}, :class => "btn btn-success status_btn" %>
  <%= link_to 'Reject Offer', {:controller => :states, :action => :reject_offer}, :class => "btn btn-danger status_btn" %>  
  <span class="pull-right">
    <p style="font-style: italic">
      You received an offer from <%= @relationship.company.name %>!
    </p>
  </span>

<% when "offer_accepted" %>
  <span class="pull-right">
    <p style="font-style: italic">
      You accepted an offer from <%= @relationship.company.name %>!
    </p>
  </span>
<% when "offer_declined" %>
  <span class="pull-right">
    <p style="font-style: italic">
      You declined an offer from <%= @relationship.company.name %>.
    </p>
  </span>
<% else %>
  <span class="pull-right">
    <p style="font-style: italic">
      If you see this message, something's not working!
    </p>
  </span>
<% end %>

app/views/shared/_state_change_buttons.html.erb
<% if @state %>
  <% case @state %>
  <% when "start" %>
    <%= link_to 'Like This Job', {:controller => :states, :action => :state_action, :job_id => @job.id, :controller_name => params[:controller], :event => "like_company"}, :class => "btn btn-success status_btn" %>
    <%= link_to 'Add Interview', new_job_interview_path(@job), :class => "btn btn-info" %>
  
  <% when "like" %>
    <%= link_to 'Unlike This Job', {:controller => :states, :action => :state_action, :job_id => @job.id, :controller_name => params[:controller], :event => "unlike_company"}, :class => "btn status_btn" %>
    <%= link_to 'Add Interview', new_job_interview_path(@job), :class => "btn btn-info" %>
  
  <% when "interviewing" %>
  <%= link_to 'Reschedule Interview', edit_interview_path(@interview.id), :class => "btn btn-warning" %>

  <% when "pending" %>
    <%= link_to 'Add Another Interview', new_job_interview_path(@job), :class => "btn btn-info" %>
    <%= link_to 'Received offer', {:controller => :states, :action => :state_action, :job_id => @job.id, :controller_name => params[:controller], :event => "receives_offer"}, :class => "btn status_btn btn-success" %>
    <%= link_to 'I\'m not interested', {:controller => :states, :action => :state_action, :job_id => @job.id, :controller_name => params[:controller], :event => "user_declines"}, :class => "btn status_btn btn-warning" %>
    <%= link_to 'Rejected!', {:controller => :states, :action => :state_action, :job_id => @job.id, :controller_name => params[:controller], :event => "company_declines"}, :class => "btn status_btn btn-danger" %>

  <% when "offer_received" %>
    <%= link_to 'Accept offer', {:controller => :states, :action => :state_action, :job_id => @job.id, :controller_name => params[:controller], :event => "accepts_offer"}, :class => "btn status_btn btn-success" %>
    <%= link_to 'Decline offer', {:controller => :states, :action => :state_action, :job_id => @job.id, :controller_name => params[:controller], :event => "declines_offer"}, :class => "btn status_btn btn-danger" %>
  
  <% when "user_decline" %>
    <span> You have decided to not pursue the opportunity as a/an <%= @job.title %> at <%= @company.name %>.</span>

  <% when "offer_declined" %>
    <span> You have declined an offer to be a <%= @job.title %> at <%= @company.name %>.</span>
  
  <% when "company_decline" %>
    <span> Sorry, but <%= @company.name %> doesn't think that there is a good fit right now.</span>
  
  <% when "offer_accepted" %>
    <h2>Congratulations. You're going to be an awesome <%= @job.title %> at <%= @job.company.name %>!</h2>
    <p style = "font-style: italic">Remember: Push code all day, every day.</p>
    <%= image_tag("http://media1.giphy.com/media/MhHXeM4SpKrpC/original.gif", :width => "300px", :style => "border-radius: 10px;")  %>
  <% end %>

<% else %>

  <%= link_to 'Like This Job', {:controller => :states, :action => :state_action, :job_id => @job.id, :controller_name => params[:controller], :event => "like_company"}, :class => "btn btn-success status_btn" %>

<% end %>
<br><hr>