config/routes.rb
HireCrm::Application.routes.draw do

  resources :records
  resources :search

  root :to => 'sessions#new'

  get 'login',     to: 'sessions#new',     as: 'login'
  post 'login',    to: 'sessions#login'
  get 'signup',    to: 'sessions#signup',  as: 'signup'
  post 'signup',   to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'dashboard', to: 'users#dashboard'

  post 'jobs/import_job' => 'jobs#import_job'
  get 'jobs/import_result' => 'jobs#import_result'

  get 'jobs/:id/state_action' => 'states#state_action', as: 'change_state'
  post 'jobs/:id/state_action' => 'states#state_action', as: 'change_state'

  get 'interviews/:interview_id/state_action' => 'states#state_action', as: 'change_state'
  post 'interviews/:interview_id/state_action' => 'states#state_action', as: 'change_state'

  post 'jobs/:id' => 'states#admin_like'

  resources :companies do 
    resources :jobs,
      :controller => 'companies/jobs',
      :only => [:new]
  end
  
  resources :jobs do 
    resources :interviews,
      :controller => 'jobs/interviews',
      :only => [:new]
  end

  resources :users do 
    resources :interviews,
      :controller => 'users/interviews',
      :only => [:new]
  end

  resources :interviews do
    resource :comment,
      :controller => 'interviews/comments',
      :only => [:new, :create]
  end

  
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id                  :integer          not null, primary key
#  name                :string(255)
#  website             :string(255)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  logo_url            :string(255)
#  crunchbase_url      :string(255)
#  blog_url            :string(255)
#  twitter_username    :string(255)
#  number_of_employees :string(255)
#  founded_year        :string(255)
#  overview            :text
#

class Company < ActiveRecord::Base
  attr_accessible :name, :website, :logo_url, :crunchbase_url, :blog_url,
                  :twitter_username, :number_of_employees, :founded_year, :overview

  has_many :relationships
  
  has_many :jobs, 			:dependent => :destroy
  
  has_many :interviews,  :through => :jobs
  has_many :records, 		:through => :relationships
  has_many :users, 			:through => :relationships

  validates_presence_of   :logo_url
  validates_presence_of   :name
  validates_presence_of   :website

  #### uncomment to enable solar ####
  # searchable do
  #   text :name
  # end

end

app/controllers/companies/jobs_controller.rb
class Companies::JobsController < ApplicationController
	before_filter :logged_in?, :only => [:index, :show, :update, :new]
  
  # GET 	=> /companies/:company_id/jobs/new/
  def new
    @job     = Job.new
    @company = Company.find(params[:company_id])

    respond_to do |format|
      format.html
      format.json { render json: @interview }
    end
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :admin?, :only => [:edit, :destroy]
  before_filter :logged_in?, :only => [:index, :show, :new, :create]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully deleted.' }
      format.json { head :no_content }
    end
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :logo_url %><br />
    <%= f.text_field :logo_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Page for <%= @company.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-header" data-original-title>
      <h2><i class="icon-picture"></i> Company Gallery</h2>
    </div>
    <div class="box-content">
      <div class="masonry-gallery">

      <% @companies.sort_by{|c| c.name }.each_with_index do |company, i| %>

        <div id="image-<%= i %>" class="masonry-thumb company-gallery">
            <div class="wrapper-cell">
              <div>
              <%= link_to image_tag(company.logo_url, :size => "150x150", :title => company.name), company_path(company) %>
              </div>
            </div>
        </div>
        
      <% end %>
                      
      </div>
    </div>
  </div><!--/span-->

</div><!--/row-->

<hr>

<!-- end: Content -->

<%= link_to 'New Company', new_company_path, :class => "btn btn-info" %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row-fluid sortable">

  <div class="box span4">
    <div class="box-content pagination-centered company_logo_div">
      <%= image_tag @company.logo_url, :size => "200x200" %>
    </div>
  </div><!--/span-->
  <div class="box span8">
    <div class="box-content">
      <h2><%= @company.name %></h2>
      <p>
        <%= raw(@company.overview) %>
      </p>               
     </div>
  </div><!--/span-->
</div><!--/row-->
<div class="row-fluid sortable">
  <div class="box span8">
    <div class="box-header">
      <h2><i class="icon-th"></i><span class="break"></span>General Information</h2>
    </div>
    <div class="box-content">
      <table>
        <tr>
          <td><strong>Website</strong></td>
          <% if @company.website == "Please update" %>
            <td><%= link_to @company.website, edit_company_path(@company), :target => "_blank" %></td> 
          <% else %>
            <td><%= link_to @company.website, @company.website, :target => "_blank" %></td>            
          <% end %>
        </tr>
        <tr>
          <td><strong>Crunchbase Profile &nbsp&nbsp</strong></td>
          <% if @company.crunchbase_url == "Please update" %>
            <td><%= link_to @company.crunchbase_url, edit_company_path(@company), :target => "_blank" %></td> 
          <% else %>
            <td><%= link_to @company.crunchbase_url, @company.crunchbase_url, :target => "_blank" %></td>
          <% end %>
        </tr>
        <tr>
          <td><strong>Blog</strong></td>
          <% if @company.blog_url == "Please update" %>
            <td><%= link_to @company.blog_url, edit_company_path(@company), :target => "_blank" %></td> 
          <% else %>
            <td><%= link_to @company.blog_url, @company.blog_url, :target => "_blank" %></td>
          <% end %>
        </tr> 
        <tr>
          <td><strong>Twitter Handle</strong></td>
          <% if @company.twitter_username == "Please update" %>
            <td><%= link_to @company.twitter_username, edit_company_path(@company), :target => "_blank" %></td> 
          <% else %>
          <td><%= link_to @company.twitter_username, "http://twitter.com/#{@company.twitter_username}", :target => "_blank" %></td>
          <% end %>
        </tr> 
        <tr>
          <td><strong>Num of Employees</strong></td>
          <% if @company.number_of_employees == "Please update" %>
            <td><%= link_to @company.number_of_employees, edit_company_path(@company), :target => "_blank" %></td> 
          <% else %>
            <td><%= @company.number_of_employees %></td>
          <% end %>
        </tr> 
        <tr>
          <td><strong>Year Founded</strong></td>
          <% if @company.founded_year == "Please update" %>
            <td><%= link_to @company.founded_year, edit_company_path(@company), :target => "_blank" %></td> 
          <% else %>
            <td><%= @company.founded_year %></td>
          <% end %>
        </tr> 
      </table>              
    </div>
  </div><!--/span-->

<!-- #  blog_url            :string(255)
#  twitter_username    :string(255)
#  number_of_employees :integer
#  founded_year        :integer
#  overview            :text -->
  
  <div class="box span4">
    <div class="box-header">
      <h2><i class="icon-th"></i><span class="break"></span>Job Openings</h2>
    </div>
    <div class="box-content">
      <% if !@company.jobs.empty? %>
      <ul>
        <% @company.jobs.each do |job| %>
          <li><%= link_to job.title, job_path(job) %></li>
        <% end %>
      </ul>  
      <% else %>   
        <p>There are currently no available jobs postings for this company.  >:(</p>
      <% end %>      
    </div>
  </div><!--/span-->
</div><!--/row-->

<% if current_user.admin? %>
  <hr>
  <h4>Upcoming Interviews</h4>

  <% if @company.interviews.empty? == true %>
  	<p><%= @company.name %> has no upcoming interviews.</p>
  <% else %>
  	<%= render :partial => "shared/interview_list", :locals => {:interview_list => @company.interviews} %>
  <% end %>

  <hr>

  <h4>Record History</h4>

  <% if @company.records.empty? == true %>
    <p><%= @company.name %> has no record history.</p>
  <% else %>
    <%= render :partial => "shared/record_list", :locals => {:record_list => @company.records} %>
  <% end %>

<% end %>

<hr>

<%= link_to 'Add New Job', new_company_job_path(@company), :class => "btn btn-info" %>

<hr>

<% if current_user.admin? %>
  <%= link_to 'Edit Company', edit_company_path(@company), :class => 'btn btn-warning' %>

  <%= link_to raw('<i class="icon-trash icon-white"></i> Delete Company'), @company, :class => 'btn btn-danger', :confirm => "Are you sure you want to delete this?", :method => :delete %>
<% end %>
<br/>

<br/><br/><br/>